// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanoPos.Infrastructure.Persistence;

#nullable disable

namespace PanoPos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PanoPosDbContext))]
    [Migration("20260402142957_AddProductVariantBarcodeCore")]
    partial class AddProductVariantBarcodeCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PanoPos.Domain.Entities.Barkod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BarkodNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BarkodTipi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UrunId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UrunVaryantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunVaryantId");

                    b.HasIndex("TenantId", "BarkodNo")
                        .IsUnique();

                    b.ToTable("Barkod", null, t =>
                        {
                            t.HasCheckConstraint("CK_Barkod_Hedef", "([UrunId] IS NOT NULL AND [UrunVaryantId] IS NULL) OR ([UrunId] IS NULL AND [UrunVaryantId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Beden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Ad");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Beden", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("VarsayilanKasaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.HasIndex("VarsayilanKasaId");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Cihaz", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Ana Kasa Cihaz",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "CIHAZ-001",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kasa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubeId", "Ad")
                        .IsUnique();

                    b.ToTable("Kasa", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KasaHareket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<int>("IslemTipi")
                        .HasColumnType("int");

                    b.Property<long>("KasaId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReferansId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferansTip")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("VardiyaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VardiyaId");

                    b.HasIndex("KasaId", "Tarih");

                    b.ToTable("KasaHareket", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kullanici", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("KilitliMi")
                        .HasColumnType("bit");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PinSonDegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AktifMi");

                    b.ToTable("Kullanici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Admin",
                            AktifMi = true,
                            BasarisizGirisSayisi = 0,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KilitliMi = false,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PinHash = "100000.AQIDBAUGBwgJCgsMDQ4PEA==.zXEe8seaNwtLmNvAYvfpAmiMOk6AXt6Jn4slCkkKXHE=",
                            PinSonDegistirmeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            Soyad = "Kullanici",
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciOturum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId", "AktifMi");

                    b.ToTable("KullaniciOturum", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("KullaniciId", "RolId")
                        .IsUnique();

                    b.ToTable("KullaniciRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciId = 1L,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolId = 1L,
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciSube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("BagliSubeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BagliSubeId");

                    b.HasIndex("KullaniciId", "BagliSubeId")
                        .IsUnique();

                    b.ToTable("KullaniciSube", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AktifMi = true,
                            BagliSubeId = 1L,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciId = 1L,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Renk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Ad");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Renk", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Admin",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Sube", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Merkez Sube",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "MRKZ",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Pano Demo Tenant",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "PANO",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Urun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrunKodu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UrunKodu")
                        .IsUnique()
                        .HasFilter("[UrunKodu] IS NOT NULL");

                    b.HasIndex("TenantId", "SubeId", "SilindiMi");

                    b.ToTable("Urun", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.UrunVaryant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool>("BarkodluMu")
                        .HasColumnType("bit");

                    b.Property<long?>("BedenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RenkId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UrunId")
                        .HasColumnType("bigint");

                    b.Property<string>("VaryantKodu")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("BedenId");

                    b.HasIndex("RenkId");

                    b.HasIndex("UrunId");

                    b.HasIndex("TenantId", "UrunId", "RenkId", "BedenId")
                        .IsUnique()
                        .HasFilter("[RenkId] IS NOT NULL AND [BedenId] IS NOT NULL");

                    b.ToTable("UrunVaryant", null, t =>
                        {
                            t.HasCheckConstraint("CK_UrunVaryant_RenkVeyaBeden", "[RenkId] IS NOT NULL OR [BedenId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Vardiya", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AcilisNakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AcilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("KasaId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("CihazId", "AktifMi");

                    b.HasIndex("KasaId", "AktifMi");

                    b.ToTable("Vardiya", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.VardiyaKapanis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("BeklenenNakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FarkTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("KartToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SayilanNakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VardiyaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("VeresiyeToplam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId")
                        .IsUnique();

                    b.ToTable("VardiyaKapanis", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Barkod", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Urun", "Urun")
                        .WithMany("Barkodlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.UrunVaryant", "UrunVaryant")
                        .WithMany("Barkodlar")
                        .HasForeignKey("UrunVaryantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Urun");

                    b.Navigation("UrunVaryant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Sube", "Sube")
                        .WithMany("Cihazlar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kasa", "VarsayilanKasa")
                        .WithMany("Cihazlar")
                        .HasForeignKey("VarsayilanKasaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sube");

                    b.Navigation("VarsayilanKasa");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KasaHareket", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kasa", "Kasa")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Vardiya", "Vardiya")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cihaz");

                    b.Navigation("Kasa");

                    b.Navigation("Kullanici");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciOturum", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("KullaniciOturumlar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciOturumlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciRol", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciRoller")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Rol", "Rol")
                        .WithMany("KullaniciRoller")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciSube", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Sube", "Sube")
                        .WithMany("KullaniciSubeler")
                        .HasForeignKey("BagliSubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciSubeler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subeler")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.UrunVaryant", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Beden", "Beden")
                        .WithMany("UrunVaryantlari")
                        .HasForeignKey("BedenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Renk", "Renk")
                        .WithMany("UrunVaryantlari")
                        .HasForeignKey("RenkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Urun", "Urun")
                        .WithMany("Varyantlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beden");

                    b.Navigation("Renk");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Vardiya", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("Vardiyalar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kasa", "Kasa")
                        .WithMany("Vardiyalar")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Kasa");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.VardiyaKapanis", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Vardiya", "Vardiya")
                        .WithOne("VardiyaKapanis")
                        .HasForeignKey("PanoPos.Domain.Entities.VardiyaKapanis", "VardiyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Beden", b =>
                {
                    b.Navigation("UrunVaryantlari");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.Navigation("KasaHareketleri");

                    b.Navigation("KullaniciOturumlar");

                    b.Navigation("Vardiyalar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kasa", b =>
                {
                    b.Navigation("Cihazlar");

                    b.Navigation("KasaHareketleri");

                    b.Navigation("Vardiyalar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciOturumlar");

                    b.Navigation("KullaniciRoller");

                    b.Navigation("KullaniciSubeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Renk", b =>
                {
                    b.Navigation("UrunVaryantlari");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Rol", b =>
                {
                    b.Navigation("KullaniciRoller");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.Navigation("Cihazlar");

                    b.Navigation("KullaniciSubeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Urun", b =>
                {
                    b.Navigation("Barkodlar");

                    b.Navigation("Varyantlar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.UrunVaryant", b =>
                {
                    b.Navigation("Barkodlar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Vardiya", b =>
                {
                    b.Navigation("KasaHareketleri");

                    b.Navigation("VardiyaKapanis");
                });
#pragma warning restore 612, 618
        }
    }
}
