// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanoPos.Infrastructure.Persistence;

#nullable disable

namespace PanoPos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PanoPosDbContext))]
    [Migration("20260406180158_AddAuditLogCore")]
    partial class AddAuditLogCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PanoPos.Domain.Entities.Adisyon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AcanCihazId")
                        .HasColumnType("bigint");

                    b.Property<long>("AcanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("AcilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("MasaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AcanCihazId");

                    b.HasIndex("AcanKullaniciId");

                    b.HasIndex("MasaId", "Durum");

                    b.HasIndex("TenantId", "SubeId", "AcilisTarihi");

                    b.ToTable("Adisyon", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Banka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubeId", "Kod")
                        .IsUnique();

                    b.ToTable("Banka", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.BankaHareket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("BankaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HareketTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kur")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TahsilatId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YerelTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankaId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("TahsilatId");

                    b.HasIndex("TenantId", "SubeId", "BankaId", "HareketTarihi");

                    b.ToTable("BankaHareket", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Barkod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BarkodNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BarkodTipi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UrunId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UrunVaryantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunVaryantId");

                    b.HasIndex("TenantId", "BarkodNo")
                        .IsUnique();

                    b.ToTable("Barkod", null, t =>
                        {
                            t.HasCheckConstraint("CK_Barkod_Hedef", "([UrunId] IS NOT NULL AND [UrunVaryantId] IS NULL) OR ([UrunId] IS NULL AND [UrunVaryantId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Beden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Ad");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Beden", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cari", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("CariKodu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CariKodu")
                        .IsUnique()
                        .HasFilter("[CariKodu] IS NOT NULL");

                    b.HasIndex("TenantId", "SubeId", "SilindiMi");

                    b.ToTable("Cari", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.CariHareket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CariId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("HareketTarihi")
                        .HasColumnType("datetime2");

                    b.Property<short>("HareketTipi")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Kur")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TahsilatId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YerelTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("TahsilatId");

                    b.HasIndex("TenantId", "SubeId", "CariId", "HareketTarihi");

                    b.ToTable("CariHareket", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("VarsayilanKasaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.HasIndex("VarsayilanKasaId");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Cihaz", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Ana Kasa Cihaz",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "CIHAZ-001",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Fatura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CariId")
                        .HasColumnType("bigint");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GenelIndirimOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GenelIndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("KapatanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Kur")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NetToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SiparisId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("SiparisId");

                    b.HasIndex("TenantId", "FaturaNo")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubeId", "Durum");

                    b.ToTable("Fatura", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.FaturaDetay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("FaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("IndirimOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SatirAraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirNetToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UrunId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UrunVaryantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunVaryantId");

                    b.ToTable("FaturaDetay", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.IslemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("BasariliMi")
                        .HasColumnType("bit");

                    b.Property<string>("ButonAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EkranAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HataKodu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("HedefId")
                        .HasColumnType("bigint");

                    b.Property<string>("HedefTablo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModulAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SureMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TenantId", "BasariliMi", "OlusturmaTarihi")
                        .IsDescending(false, false, true);

                    b.HasIndex("TenantId", "KullaniciId", "OlusturmaTarihi")
                        .IsDescending(false, false, true);

                    b.HasIndex("TenantId", "SubeId", "OlusturmaTarihi")
                        .IsDescending(false, false, true);

                    b.ToTable("IslemLog", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kasa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubeId", "Ad")
                        .IsUnique();

                    b.ToTable("Kasa", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KasaHareket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<int>("IslemTipi")
                        .HasColumnType("int");

                    b.Property<long>("KasaId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReferansId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferansTip")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("VardiyaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("VardiyaId");

                    b.HasIndex("KasaId", "Tarih");

                    b.ToTable("KasaHareket", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kullanici", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("KilitliMi")
                        .HasColumnType("bit");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PinSonDegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AktifMi");

                    b.ToTable("Kullanici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Admin",
                            AktifMi = true,
                            BasarisizGirisSayisi = 0,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KilitliMi = false,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PinHash = "100000.AQIDBAUGBwgJCgsMDQ4PEA==.zXEe8seaNwtLmNvAYvfpAmiMOk6AXt6Jn4slCkkKXHE=",
                            PinSonDegistirmeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            Soyad = "Kullanici",
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciOturum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId", "AktifMi");

                    b.ToTable("KullaniciOturum", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("KullaniciId", "RolId")
                        .IsUnique();

                    b.ToTable("KullaniciRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciId = 1L,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolId = 1L,
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciSube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("BagliSubeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BagliSubeId");

                    b.HasIndex("KullaniciId", "BagliSubeId")
                        .IsUnique();

                    b.ToTable("KullaniciSube", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AktifMi = true,
                            BagliSubeId = 1L,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciId = 1L,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Masa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MasaDurumId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MasaDurumId");

                    b.HasIndex("TenantId", "SubeId", "SilindiMi");

                    b.ToTable("Masa", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.MasaDurum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MasaDurum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Bos",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 2L,
                            Ad = "Dolu",
                            AktifMi = true
                        },
                        new
                        {
                            Id = 3L,
                            Ad = "Rezerve",
                            AktifMi = true
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Renk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Ad");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Renk", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Admin",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Siparis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("AdisyonId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CariId")
                        .HasColumnType("bigint");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("GenelIndirimOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GenelIndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Kur")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("NetToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("SiparisTipi")
                        .HasColumnType("smallint");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("AdisyonId", "Durum");

                    b.HasIndex("TenantId", "SiparisNo")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubeId", "Durum");

                    b.ToTable("Siparis", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.SiparisDetay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("IndirimOrani")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("IndirimTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SatirAraToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirNetToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SatirToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SiparisId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UrunId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UrunVaryantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunVaryantId");

                    b.ToTable("SiparisDetay", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Sube", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Merkez Sube",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "MRKZ",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tahsilat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("FaturaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Kur")
                        .HasColumnType("decimal(18,6)");

                    b.Property<short>("OdemeTipi")
                        .HasColumnType("smallint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParaBirimKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TahsilatFisNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TahsilatTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YerelTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.HasIndex("TenantId", "TahsilatFisNo")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubeId", "TahsilatTarihi");

                    b.ToTable("Tahsilat", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Pano Demo Tenant",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "PANO",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Urun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrunKodu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UrunKodu")
                        .IsUnique()
                        .HasFilter("[UrunKodu] IS NOT NULL");

                    b.HasIndex("TenantId", "SubeId", "SilindiMi");

                    b.ToTable("Urun", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.UrunVaryant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<bool>("BarkodluMu")
                        .HasColumnType("bit");

                    b.Property<long?>("BedenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RenkId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UrunId")
                        .HasColumnType("bigint");

                    b.Property<string>("VaryantKodu")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("BedenId");

                    b.HasIndex("RenkId");

                    b.HasIndex("UrunId");

                    b.HasIndex("TenantId", "UrunId", "RenkId", "BedenId")
                        .IsUnique()
                        .HasFilter("[RenkId] IS NOT NULL AND [BedenId] IS NOT NULL");

                    b.ToTable("UrunVaryant", null, t =>
                        {
                            t.HasCheckConstraint("CK_UrunVaryant_RenkVeyaBeden", "[RenkId] IS NOT NULL OR [BedenId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Vardiya", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AcilisNakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AcilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("KasaId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("CihazId", "AktifMi");

                    b.HasIndex("KasaId", "AktifMi");

                    b.ToTable("Vardiya", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.VardiyaKapanis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("BeklenenNakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FarkTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("KartToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SayilanNakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("VardiyaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("VeresiyeToplam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId")
                        .IsUnique();

                    b.ToTable("VardiyaKapanis", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Adisyon", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", null)
                        .WithMany()
                        .HasForeignKey("AcanCihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("AcanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Masa", "Masa")
                        .WithMany("Adisyonlar")
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Masa");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.BankaHareket", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Banka", "Banka")
                        .WithMany()
                        .HasForeignKey("BankaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Tahsilat", "Tahsilat")
                        .WithMany()
                        .HasForeignKey("TahsilatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Banka");

                    b.Navigation("Fatura");

                    b.Navigation("Tahsilat");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Barkod", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Urun", "Urun")
                        .WithMany("Barkodlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.UrunVaryant", "UrunVaryant")
                        .WithMany("Barkodlar")
                        .HasForeignKey("UrunVaryantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Urun");

                    b.Navigation("UrunVaryant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.CariHareket", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Tahsilat", "Tahsilat")
                        .WithMany()
                        .HasForeignKey("TahsilatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cari");

                    b.Navigation("Fatura");

                    b.Navigation("Tahsilat");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Sube", "Sube")
                        .WithMany("Cihazlar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kasa", "VarsayilanKasa")
                        .WithMany("Cihazlar")
                        .HasForeignKey("VarsayilanKasaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sube");

                    b.Navigation("VarsayilanKasa");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Siparis", "Siparis")
                        .WithMany()
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cari");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.FaturaDetay", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Detaylar")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.UrunVaryant", "UrunVaryant")
                        .WithMany()
                        .HasForeignKey("UrunVaryantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fatura");

                    b.Navigation("Urun");

                    b.Navigation("UrunVaryant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.IslemLog", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany()
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cihaz");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KasaHareket", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kasa", "Kasa")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Vardiya", "Vardiya")
                        .WithMany("KasaHareketleri")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cihaz");

                    b.Navigation("Kasa");

                    b.Navigation("Kullanici");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciOturum", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("KullaniciOturumlar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciOturumlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciRol", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciRoller")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Rol", "Rol")
                        .WithMany("KullaniciRoller")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciSube", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Sube", "Sube")
                        .WithMany("KullaniciSubeler")
                        .HasForeignKey("BagliSubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciSubeler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Masa", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.MasaDurum", "MasaDurum")
                        .WithMany("Masalar")
                        .HasForeignKey("MasaDurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasaDurum");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Siparis", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Adisyon", "Adisyon")
                        .WithMany()
                        .HasForeignKey("AdisyonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Adisyon");

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.SiparisDetay", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Siparis", "Siparis")
                        .WithMany("Detaylar")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.UrunVaryant", "UrunVaryant")
                        .WithMany()
                        .HasForeignKey("UrunVaryantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Siparis");

                    b.Navigation("Urun");

                    b.Navigation("UrunVaryant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subeler")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tahsilat", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.UrunVaryant", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Beden", "Beden")
                        .WithMany("UrunVaryantlari")
                        .HasForeignKey("BedenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Renk", "Renk")
                        .WithMany("UrunVaryantlari")
                        .HasForeignKey("RenkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PanoPos.Domain.Entities.Urun", "Urun")
                        .WithMany("Varyantlar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beden");

                    b.Navigation("Renk");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Vardiya", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("Vardiyalar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kasa", "Kasa")
                        .WithMany("Vardiyalar")
                        .HasForeignKey("KasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Kasa");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.VardiyaKapanis", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Vardiya", "Vardiya")
                        .WithOne("VardiyaKapanis")
                        .HasForeignKey("PanoPos.Domain.Entities.VardiyaKapanis", "VardiyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Beden", b =>
                {
                    b.Navigation("UrunVaryantlari");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.Navigation("KasaHareketleri");

                    b.Navigation("KullaniciOturumlar");

                    b.Navigation("Vardiyalar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kasa", b =>
                {
                    b.Navigation("Cihazlar");

                    b.Navigation("KasaHareketleri");

                    b.Navigation("Vardiyalar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciOturumlar");

                    b.Navigation("KullaniciRoller");

                    b.Navigation("KullaniciSubeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Masa", b =>
                {
                    b.Navigation("Adisyonlar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.MasaDurum", b =>
                {
                    b.Navigation("Masalar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Renk", b =>
                {
                    b.Navigation("UrunVaryantlari");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Rol", b =>
                {
                    b.Navigation("KullaniciRoller");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Siparis", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.Navigation("Cihazlar");

                    b.Navigation("KullaniciSubeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Urun", b =>
                {
                    b.Navigation("Barkodlar");

                    b.Navigation("Varyantlar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.UrunVaryant", b =>
                {
                    b.Navigation("Barkodlar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Vardiya", b =>
                {
                    b.Navigation("KasaHareketleri");

                    b.Navigation("VardiyaKapanis");
                });
#pragma warning restore 612, 618
        }
    }
}
