// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanoPos.Infrastructure.Persistence;

#nullable disable

namespace PanoPos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PanoPosDbContext))]
    [Migration("20260402120933_InitialSystemTables")]
    partial class InitialSystemTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Cihaz", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Ana Kasa Cihaz",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "CIHAZ-001",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kullanici", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Pin")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Admin",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Pin = "1234",
                            SilindiMi = false,
                            Soyad = "Kullanici",
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciOturum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("CihazId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CihazId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciOturum", (string)null);
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("KullaniciId", "RolId")
                        .IsUnique();

                    b.ToTable("KullaniciRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciId = 1L,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RolId = 1L,
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciSube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("BagliSubeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BagliSubeId");

                    b.HasIndex("KullaniciId", "BagliSubeId")
                        .IsUnique();

                    b.ToTable("KullaniciSube", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AktifMi = true,
                            BagliSubeId = 1L,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            KullaniciId = 1L,
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Admin",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kod")
                        .IsUnique();

                    b.ToTable("Sube", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Merkez Sube",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "MRKZ",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GuncelleyenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("OlusturanKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SilenKullaniciId")
                        .HasColumnType("bigint");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubeId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ad = "Pano Demo Tenant",
                            AktifMi = true,
                            GuncellemeTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kod = "PANO",
                            OlusturmaTarihi = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SilindiMi = false,
                            SubeId = 1L,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Sube", "Sube")
                        .WithMany("Cihazlar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciOturum", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Cihaz", "Cihaz")
                        .WithMany("KullaniciOturumlar")
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciOturumlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciRol", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciRoller")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Rol", "Rol")
                        .WithMany("KullaniciRoller")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.KullaniciSube", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Sube", "Sube")
                        .WithMany("KullaniciSubeler")
                        .HasForeignKey("BagliSubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PanoPos.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciSubeler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.HasOne("PanoPos.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subeler")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Cihaz", b =>
                {
                    b.Navigation("KullaniciOturumlar");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciOturumlar");

                    b.Navigation("KullaniciRoller");

                    b.Navigation("KullaniciSubeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Rol", b =>
                {
                    b.Navigation("KullaniciRoller");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Sube", b =>
                {
                    b.Navigation("Cihazlar");

                    b.Navigation("KullaniciSubeler");
                });

            modelBuilder.Entity("PanoPos.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subeler");
                });
#pragma warning restore 612, 618
        }
    }
}
